import React, { useState, useRef, useEffect } from 'react';
import { Layout } from './components/Layout';
import { PipelineVisualizer } from './components/PipelineVisualizer';
import { ResultViewer } from './components/ResultViewer';
import { KnowledgeGraph } from './components/KnowledgeGraph';
import { IdeaInput } from './components/IdeaInput';
import { ConfigPanel } from './components/ConfigPanel';
import { 
  AppConfig, 
  PipelineStatus, 
  PipelineStep, 
  PipelineLog, 
  GeneratedStory, 
  ReviewScore,
  Language
} from './types';
import { api } from './services/api';

// Translations Dictionary
const translations = {
  en: {
    nav: {
      dashboard: "Dashboard",
      results: "Paper Viewer",
      kg: "Knowledge Graph",
      settings: "Configuration"
    },
    common: {
      close: "Close"
    },
    social: {
      wechat_group: "Join WeChat Group",
      scan_qr: "Scan the QR code to join our community discussion."
    },
    dashboard: {
      title: "Research Dashboard",
      subtitle: "Idea2Paper Pipeline Control Center",
      status_idle: "Ready",
      status_running: "Running",
      status_complete: "Complete",
      status_error: "Error"
    },
    input: {
      title: "Start Your Research Journey",
      subtitle: "Enter a raw research concept, and Idea2Paper will structure it into a complete scientific narrative.",
      label: "Research Idea / Abstract Concept",
      placeholder: "e.g., We want to explore how Large Language Models can be used to simulate social dynamics in a small village...",
      try_example: "Try an example:",
      btn_generate: "Generate Story",
      btn_running: "Processing..."
    },
    pipeline: {
      title: "Pipeline Execution",
      subtitle: "Transforming idea to scientific narrative",
      waiting: "Waiting to start pipeline...",
      terminate: "Terminate",
      terminated_msg: "Pipeline terminated by user.",
      terminated_desc: "The process was manually stopped.",
      elapsed: "Elapsed Time",
      notice: "This process may take several tens of minutes. Please be patient. If you encounter any errors, please report them to us on GitHub. Thank you for using!"
    },
    results: {
      no_story: "No story generated yet.",
      run_hint: "Run the pipeline from the Dashboard to see results.",
      generated_by: "Generated by Idea2Story",
      abstract: "Abstract",
      intro: "1. Introduction",
      method: "2. Methodology",
      exp: "3. Experiments",
      contrib: "4. Contributions",
      export: "Export Options",
      anchored_review: "Anchored Review",
      about_anchor: "About Anchored Review",
      about_anchor_desc: "Scores are determined by comparing your story against ICLR anchor papers with known ratings using a deterministic fit."
    },
    config: {
      headers: {
        connection: "Connection & Credentials",
        llm: "LLM Configuration",
        embedding: "Embedding Configuration",
        pipeline: "Pipeline Control",
        advanced: "Advanced Logic",
        temperatures: "LLM Temperatures (Overrides)"
      },
      labels: {
        api_key: "Backend API Key",
        base_url: "Backend Base URL",
        silicon_key: "SiliconFlow API Key",
        llm_url: "LLM API URL",
        llm_model: "LLM Model",
        embed_url: "Embedding API URL",
        embed_model: "Embedding Model",
        mode_mock: "Mock Mode",
        mode_real: "Real API Mode",
        enable_logging: "Enable Run Logging",
        enable_results: "Enable Result Bundling",
        novelty_check: "Novelty Check (Phase 1)",
        novelty_action: "Action on High Similarity",
        verification: "Final Verification (Phase 4)",
        collision_th: "Collision Threshold",
        idea_packaging: "Idea Packaging",
        critic_strict: "Strict JSON Critic",
        auto_index: "Auto Build Indexes"
      },
      descriptions: {
        silicon_key: "Used for both LLM chat and Embedding if not overridden.",
        novelty: "Check against nodes_paper.json for duplicates.",
        verification: "Perform final collision check before completion.",
        idea_packaging: "Enable pattern-guided double recall.",
        critic: "Retry on invalid JSON to ensure quality."
      }
    },
    kg: {
      title: "Knowledge Graph Explorer",
      desc: "The interactive node explorer for the ICLR dataset is currently being indexed. Please run the pipeline to view local graph connections extracted for your specific idea."
    },
    steps: {
      [PipelineStep.INIT]: "Init",
      [PipelineStep.RETRIEVAL]: "Retrieval",
      [PipelineStep.GENERATION]: "Generation",
      [PipelineStep.REVIEW]: "Review",
      [PipelineStep.VALIDATION]: "Validation",
      [PipelineStep.DONE]: "Done",
      [PipelineStep.ERROR]: "Error"
    }
  },
  zh: {
    nav: {
      dashboard: "仪表盘",
      results: "论文预览",
      kg: "知识图谱",
      settings: "系统配置"
    },
    common: {
      close: "关闭"
    },
    social: {
      wechat_group: "加入微信交流群",
      scan_qr: "扫描二维码加入我们的社区讨论。"
    },
    dashboard: {
      title: "科研仪表盘",
      subtitle: "Idea2Paper 流程控制中心",
      status_idle: "就绪",
      status_running: "运行中",
      status_complete: "完成",
      status_error: "错误"
    },
    input: {
      title: "开启科研之旅",
      subtitle: "输入原始的研究想法，Idea2Paper 将其转化为完整的科学叙事。",
      label: "研究想法 / 摘要概念",
      placeholder: "例如：我们想探索大语言模型如何用于模拟小村庄中的社会动态...",
      try_example: "尝试示例：",
      btn_generate: "生成故事",
      btn_running: "处理中..."
    },
    pipeline: {
      title: "流程执行",
      subtitle: "正在将想法转化为科学叙事",
      waiting: "等待启动流程...",
      terminate: "终止",
      terminated_msg: "流程已由用户终止。",
      terminated_desc: "操作被手动停止。",
      elapsed: "耗时",
      notice: "该过程可能需要几十分钟，请耐心等候。如有报错，请在 GitHub 反馈给我们。感谢使用！"
    },
    results: {
      no_story: "尚未生成故事。",
      run_hint: "请在仪表盘运行流程以查看结果。",
      generated_by: "由 Idea2Story 生成",
      abstract: "摘要",
      intro: "1. 引言",
      method: "2. 方法论",
      exp: "3. 实验",
      contrib: "4. 贡献",
      export: "导出选项",
      anchored_review: "锚点评审",
      about_anchor: "关于锚点评审",
      about_anchor_desc: "分数是通过将您的故事与已知评分的 ICLR 锚点论文进行确定性拟合来计算的。"
    },
    config: {
      headers: {
        connection: "连接与凭证",
        llm: "LLM 模型配置",
        embedding: "Embedding 配置",
        pipeline: "流程控制",
        advanced: "高级逻辑设置",
        temperatures: "温度参数 (覆盖)"
      },
      labels: {
        api_key: "后端 API Key",
        base_url: "后端服务地址",
        silicon_key: "SiliconFlow API Key",
        llm_url: "LLM API 地址",
        llm_model: "LLM 模型名称",
        embed_url: "Embedding API 地址",
        embed_model: "Embedding 模型",
        mode_mock: "Mock 模式",
        mode_real: "真实 API 模式",
        enable_logging: "启用运行日志",
        enable_results: "启用结果归档",
        novelty_check: "新颖性检查 (Phase 1)",
        novelty_action: "高相似度动作",
        verification: "最终验证 (Phase 4)",
        collision_th: "冲突阈值",
        idea_packaging: "Idea Packaging",
        critic_strict: "严格 JSON 评审",
        auto_index: "自动构建索引"
      },
      descriptions: {
        silicon_key: "用于 LLM 对话和 Embedding（除非被单独覆盖）。",
        novelty: "针对 nodes_paper.json 检查重复项。",
        verification: "在完成前执行最终冲突检查。",
        idea_packaging: "启用模式引导的双重召回机制。",
        critic: "遇到无效 JSON 时重试以确保质量。"
      }
    },
    kg: {
      title: "知识图谱探索器",
      desc: "ICLR 数据集的交互式节点探索器目前正在索引中。请运行流程以查看为您特定想法提取的本地图连接。"
    },
    steps: {
      [PipelineStep.INIT]: "初始化",
      [PipelineStep.RETRIEVAL]: "知识检索",
      [PipelineStep.GENERATION]: "故事生成",
      [PipelineStep.REVIEW]: "评审润色",
      [PipelineStep.VALIDATION]: "验证检查",
      [PipelineStep.DONE]: "完成",
      [PipelineStep.ERROR]: "错误"
    }
  }
};

function App() {
  // Navigation State
  const [activeTab, setActiveTab] = useState('dashboard');
  const [lang, setLang] = useState<Language>('en');

  // Helper for translations
  const t = translations[lang];

  // Load config from localStorage or use defaults
  const getInitialConfig = (): AppConfig => {
    try {
      const savedConfig = localStorage.getItem('idea2paper_config');
      if (savedConfig) {
        const parsed = JSON.parse(savedConfig);
        // Merge with defaults to ensure all fields exist
        return {
          ...defaultConfig,
          ...parsed,
          endpoints: { ...defaultConfig.endpoints, ...(parsed.endpoints || {}) },
          llmTemperatures: { ...defaultConfig.llmTemperatures, ...(parsed.llmTemperatures || {}) },
          ideaPackaging: { ...defaultConfig.ideaPackaging, ...(parsed.ideaPackaging || {}) },
          logging: { ...defaultConfig.logging, ...(parsed.logging || {}) },
          results: { ...defaultConfig.results, ...(parsed.results || {}) },
          critic: { ...defaultConfig.critic, ...(parsed.critic || {}) },
          passRule: { ...defaultConfig.passRule, ...(parsed.passRule || {}) },
          anchors: { ...defaultConfig.anchors, ...(parsed.anchors || {}) },
          novelty: { ...defaultConfig.novelty, ...(parsed.novelty || {}) },
          verification: { ...defaultConfig.verification, ...(parsed.verification || {}) },
          index: { ...defaultConfig.index, ...(parsed.index || {}) },
          recall: { ...defaultConfig.recall, ...(parsed.recall || {}) },
        };
      }
    } catch (error) {
      console.error('Failed to load config from localStorage:', error);
    }
    return defaultConfig;
  };

  const defaultConfig: AppConfig = {
    // System
    apiKey: '',
    baseUrl: 'http://localhost:8080',
    endpoints: {
      runPipeline: '/api/runs',
      checkStatus: '/api/runs',
      cancelPipeline: '/api/runs',
      queryGraph: '/kg/query',
      exportResult: '/paper/export'
    },
    useMock: false, // Real API mode - connect to backend
    theme: 'light',

    // SiliconFlow
    siliconFlowApiKey: '',

    // LLM
    llmUrl: 'https://api.siliconflow.cn/v1/chat/completions',
    llmModel: 'Pro/zai-org/GLM-4.7',
    llmTemperatures: {
      default: 0.7,
      storyGenerator: 0.7,
      storyGeneratorRewrite: 0.3,
      storyReflector: 0.5,
      patternSelector: 0.3,
      ideaFusion: 0.7,
      ideaFusionStage2: 0.8,
      ideaFusionStage3: 0.9,
      criticMain: 0.0,
      criticRepair: 0.0,
      criticAnchored: 0.3,
      ideaPackagingParse: 0.0,
      ideaPackagingPatternGuided: 0.3,
      ideaPackagingJudge: 0.0
    },

    // Embedding
    embeddingUrl: 'https://api.siliconflow.cn/v1/embeddings',
    embeddingModel: 'Qwen/Qwen3-Embedding-8B',
    embeddingApiKey: '',
    indexDirMode: 'auto_profile',

    // Idea Packaging
    ideaPackaging: {
      enable: false,
      topNPatterns: 5,
      maxExemplarPapers: 8,
      candidateK: 3,
      selectMode: 'llm_then_recall',
      forceEnQuery: true
    },

    // Logging & Results
    logging: {
      enable: true,
      logDir: '',
      maxTextChars: 20000
    },
    results: {
      enable: true,
      resultsDir: ''
    },

    // Critic
    critic: {
      strictJson: true,
      jsonRetries: 2
    },

    // Pass Rule
    passRule: {
      mode: 'two_of_three_q75_and_avg_ge_q50',
      minPatternPapers: 20,
      fallback: 'global',
      score: 7.0
    },

    // Anchors
    anchors: {
      densifyEnable: false,
      quantiles: '0.1,0.25,0.5,0.75,0.9'
    },

    // Novelty
    novelty: {
      enable: true,
      autoBuildIndex: true,
      buildBatchSize: 32,
      action: 'pivot',
      maxPivots: 2
    },

    // Verification
    verification: {
      enable: true,
      collisionThreshold: 0.88
    },

    // Index
    index: {
      autoPrepare: true,
      allowBuild: true
    },

    // Recall
    recall: {
      auditEnable: true,
      auditTopN: 50
    }
  };

  // Config State - Initialized from localStorage or defaults
  const [config, setConfig] = useState<AppConfig>(getInitialConfig());

  // Save config to localStorage whenever it changes
  useEffect(() => {
    try {
      localStorage.setItem('idea2paper_config', JSON.stringify(config));
    } catch (error) {
      console.error('Failed to save config to localStorage:', error);
    }
  }, [config]);

  // Apply Theme Effect
  useEffect(() => {
    if (config.theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [config.theme]);

  // Toggle Theme Function
  const toggleTheme = () => {
    setConfig(prev => ({
      ...prev,
      theme: prev.theme === 'light' ? 'dark' : 'light'
    }));
  };

  // Pipeline State
  const [status, setStatus] = useState<PipelineStatus>(PipelineStatus.IDLE);
  const [currentStep, setCurrentStep] = useState<PipelineStep>(PipelineStep.INIT);
  const [logs, setLogs] = useState<PipelineLog[]>([]);
  const [currentRunId, setCurrentRunId] = useState<string | null>(() => {
    // Restore currentRunId from localStorage on page load
    const saved = localStorage.getItem('idea2paper_current_run');
    return saved ? JSON.parse(saved).runId : null;
  });
  const [showOrphanedRunBanner, setShowOrphanedRunBanner] = useState<boolean>(() => {
    // Check if there's an orphaned run on page load
    const saved = localStorage.getItem('idea2paper_current_run');
    return saved !== null;
  });

  // Timer State
  const [elapsedTime, setElapsedTime] = useState('00:00');
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const startTimeRef = useRef<number | null>(null);

  // Abort Controller for stopping pipeline
  const abortControllerRef = useRef<AbortController | null>(null);
  
  // Results State
  const [story, setStory] = useState<GeneratedStory | null>(null);
  const [reviews, setReviews] = useState<ReviewScore[]>([]);

  // Timer Effect
  useEffect(() => {
    if (status === PipelineStatus.RUNNING) {
      startTimeRef.current = Date.now();
      setElapsedTime('00:00');
      timerRef.current = setInterval(() => {
        if (startTimeRef.current) {
            const diff = Math.floor((Date.now() - startTimeRef.current) / 1000);
            const mins = Math.floor(diff / 60).toString().padStart(2, '0');
            const secs = (diff % 60).toString().padStart(2, '0');
            setElapsedTime(`${mins}:${secs}`);
        }
      }, 1000);
    } else {
        if (timerRef.current) clearInterval(timerRef.current);
        // Do not reset elapsed time on complete/error so user can see how long it took
        if (status === PipelineStatus.IDLE) {
           setElapsedTime('00:00');
        }
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [status]);

  // Save/clear current run state in localStorage
  useEffect(() => {
    if (currentRunId && status === PipelineStatus.RUNNING) {
      // Save running pipeline info
      localStorage.setItem('idea2paper_current_run', JSON.stringify({
        runId: currentRunId,
        startTime: startTimeRef.current,
        status: status
      }));
    } else if (status === PipelineStatus.COMPLETE || status === PipelineStatus.ERROR || status === PipelineStatus.IDLE) {
      // Clear when pipeline finishes or is idle
      localStorage.removeItem('idea2paper_current_run');
    }
  }, [currentRunId, status]);

  const handleStartPipeline = async (idea: string) => {
    // Validate critical configuration before starting
    const missingFields: string[] = [];

    if (!config.siliconFlowApiKey || config.siliconFlowApiKey.trim() === '') {
      missingFields.push(lang === 'en' ? 'SiliconFlow API Key' : 'SiliconFlow API Key');
    }
    if (!config.llmUrl || config.llmUrl.trim() === '') {
      missingFields.push(lang === 'en' ? 'LLM API URL' : 'LLM API URL');
    }
    if (!config.llmModel || config.llmModel.trim() === '') {
      missingFields.push(lang === 'en' ? 'LLM Model' : 'LLM Model');
    }
    if (!config.embeddingUrl || config.embeddingUrl.trim() === '') {
      missingFields.push(lang === 'en' ? 'Embedding API URL' : 'Embedding API URL');
    }
    if (!config.embeddingModel || config.embeddingModel.trim() === '') {
      missingFields.push(lang === 'en' ? 'Embedding Model' : 'Embedding Model');
    }
    if (!config.embeddingApiKey || config.embeddingApiKey.trim() === '') {
      missingFields.push(lang === 'en' ? 'Embedding API Key' : 'Embedding API Key');
    }

    if (missingFields.length > 0) {
      const fieldsList = missingFields.map(f => `  • ${f}`).join('\n');
      const message = lang === 'en'
        ? `⚠️ Configuration Required\n\nThe following required fields are missing:\n\n${fieldsList}\n\nPlease configure these settings before running the pipeline.\n\nClick OK to go to Settings page.`
        : `⚠️ 需要配置\n\n以下必填字段缺失：\n\n${fieldsList}\n\n请先在配置页面设置这些字段后再运行流水线。\n\n点击确定前往配置页面。`;

      if (confirm(message)) {
        setActiveTab('settings');
      }
      return;
    }

    // Reset state
    if (abortControllerRef.current) {
        abortControllerRef.current.abort();
    }
    const ac = new AbortController();
    abortControllerRef.current = ac;

    setStatus(PipelineStatus.RUNNING);
    setLogs([]);
    setStory(null);
    setCurrentStep(PipelineStep.INIT);
    setCurrentRunId(null);

    try {
      // Execute Pipeline via API Service
      const result = await api.runPipeline(
        idea,
        lang,
        config,
        {
            onLog: (log) => {
                setLogs(prev => [...prev, log]);
                setCurrentStep(log.step);
            },
            onRunIdReceived: (uiRunId) => {
                setCurrentRunId(uiRunId);
            }
        },
        ac.signal
      );

      setStory(result.story);
      setReviews(result.reviews);
      setStatus(PipelineStatus.COMPLETE);

      // Auto-switch to results tab after short delay
      setTimeout(() => {
        if (!ac.signal.aborted) {
           setActiveTab('results');
        }
      }, 1500);

    } catch (error: any) {
      if (error.name === 'AbortError') {
         // Handle manual termination
         setStatus(PipelineStatus.ERROR);
         setLogs(prev => [...prev, {
            timestamp: new Date().toLocaleTimeString(),
            step: PipelineStep.ERROR,
            message: t.pipeline.terminated_msg,
            details: t.pipeline.terminated_desc
         }]);
      } else {
        console.error(error);
        setStatus(PipelineStatus.ERROR);
        setLogs(prev => [...prev, {
            timestamp: new Date().toLocaleTimeString(),
            step: PipelineStep.ERROR,
            message: lang === 'en' ? "Pipeline failed" : "流程失败",
            details: error.message || (lang === 'en' ? "An unexpected error occurred." : "发生了意外错误。")
        }]);
      }
    } finally {
        if (abortControllerRef.current === ac) {
            abortControllerRef.current = null;
        }
    }
  };

  const handleStopPipeline = async () => {
    // Abort the fetch request
    if (abortControllerRef.current) {
        abortControllerRef.current.abort();
    }

    // Terminate the backend process
    if (currentRunId) {
        const terminated = await api.terminatePipeline(currentRunId, config);
        if (terminated) {
            console.log('Pipeline terminated successfully');
        } else {
            console.error('Failed to terminate pipeline');
        }
    }
  };

  const handleTerminateOrphanedRun = async () => {
    if (currentRunId) {
      const terminated = await api.terminatePipeline(currentRunId, config);
      if (terminated) {
        console.log('Orphaned pipeline terminated successfully');
        setShowOrphanedRunBanner(false);
        setCurrentRunId(null);
        localStorage.removeItem('idea2paper_current_run');
      } else {
        console.error('Failed to terminate orphaned pipeline');
      }
    }
  };

  const handleDismissOrphanedBanner = () => {
    setShowOrphanedRunBanner(false);
    localStorage.removeItem('idea2paper_current_run');
    setCurrentRunId(null);
  };

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return (
          <div className="space-y-8 animate-in fade-in duration-500">
             <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">{t.dashboard.title}</h1>
                <p className="text-slate-500 dark:text-slate-400 mt-1 font-medium">{t.dashboard.subtitle}</p>
              </div>
              <div className="flex items-center gap-3">
                 <div className={`px-4 py-1.5 rounded-full text-xs font-bold flex items-center gap-2 border shadow-sm ${
                    status === PipelineStatus.RUNNING ? 'bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800' :
                    status === PipelineStatus.COMPLETE ? 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300 dark:border-green-800' :
                    'bg-white text-slate-500 border-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:border-slate-700'
                 }`}>
                    <div className={`w-2 h-2 rounded-full ${
                        status === PipelineStatus.RUNNING ? 'bg-blue-500 animate-pulse' :
                        status === PipelineStatus.COMPLETE ? 'bg-green-500' :
                        status === PipelineStatus.ERROR ? 'bg-red-500' :
                        'bg-slate-300 dark:bg-slate-600'
                    }`}></div>
                    {status === PipelineStatus.IDLE ? t.dashboard.status_idle : 
                     status === PipelineStatus.RUNNING ? t.dashboard.status_running :
                     status === PipelineStatus.COMPLETE ? t.dashboard.status_complete :
                     t.dashboard.status_error}
                 </div>
              </div>
            </div>

            <IdeaInput 
              onSubmit={handleStartPipeline} 
              isLoading={status === PipelineStatus.RUNNING}
              t={t}
              lang={lang}
            />

            {(status !== PipelineStatus.IDLE) && (
              <PipelineVisualizer
                status={status}
                currentStep={currentStep}
                logs={logs}
                t={t}
                onStop={handleStopPipeline}
                elapsedTime={elapsedTime}
                runId={currentRunId}
                config={config}
              />
            )}
          </div>
        );
      case 'results':
        return (
          <div className="animate-in fade-in duration-500">
            <ResultViewer
              story={story}
              reviews={reviews}
              t={t}
              config={config}
              onLoadResult={(result) => {
                setStory(result.story);
                setReviews(result.reviews);
              }}
            />
          </div>
        );
      case 'settings':
        return (
          <div className="animate-in fade-in duration-500">
             <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white mb-8 tracking-tight">{t.nav.settings}</h1>
             <ConfigPanel config={config} setConfig={setConfig} t={t} />
          </div>
        );
      case 'kg':
        return (
          <div className="animate-in fade-in duration-500">
            <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white mb-8 tracking-tight">{t.kg.title}</h1>
            <KnowledgeGraph config={config} t={t} />
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <Layout
      activeTab={activeTab}
      onTabChange={setActiveTab}
      lang={lang}
      setLang={setLang}
      t={t}
      theme={config.theme}
      onThemeToggle={toggleTheme}
    >
      {/* Orphaned Run Banner */}
      {showOrphanedRunBanner && currentRunId && (
        <div className="mb-6 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-2xl p-4 animate-in slide-in-from-top duration-300">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-3 flex-1">
              <div className="p-2 bg-amber-100 dark:bg-amber-900/40 rounded-lg">
                <svg className="w-5 h-5 text-amber-600 dark:text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-amber-900 dark:text-amber-200 mb-1">
                  {lang === 'en' ? 'Running Pipeline Detected' : '检测到运行中的Pipeline'}
                </h3>
                <p className="text-sm text-amber-700 dark:text-amber-300 mb-3">
                  {lang === 'en'
                    ? `A pipeline (ID: ${currentRunId}) was running before the page was refreshed. You can terminate it or dismiss this message if it has already completed.`
                    : `页面刷新前有一个正在运行的pipeline（ID: ${currentRunId}）。你可以终止它，或者如果它已经完成则忽略此消息。`
                  }
                </p>
                <div className="flex gap-2">
                  <button
                    onClick={handleTerminateOrphanedRun}
                    className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white text-sm font-medium rounded-lg transition-colors"
                  >
                    {lang === 'en' ? 'Terminate Pipeline' : '终止Pipeline'}
                  </button>
                  <button
                    onClick={handleDismissOrphanedBanner}
                    className="px-4 py-2 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-amber-900 dark:text-amber-200 text-sm font-medium rounded-lg border border-amber-200 dark:border-amber-700 transition-colors"
                  >
                    {lang === 'en' ? 'Dismiss' : '忽略'}
                  </button>
                </div>
              </div>
            </div>
            <button
              onClick={handleDismissOrphanedBanner}
              className="p-1 hover:bg-amber-100 dark:hover:bg-amber-900/40 rounded-lg transition-colors"
            >
              <svg className="w-5 h-5 text-amber-600 dark:text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      )}

      {renderContent()}
    </Layout>
  );
}

export default App;