import React, { useState, useEffect } from 'react';
import { GeneratedStory, ReviewScore, AppConfig, PipelineResult } from '../types';
import { Download, Star, Quote, History } from 'lucide-react';
import { api } from '../services/api';

interface ResultViewerProps {
  story: GeneratedStory | null;
  reviews: ReviewScore[];
  t: any;
  config: AppConfig;
  onLoadResult: (result: PipelineResult) => void;
}

export const ResultViewer: React.FC<ResultViewerProps> = ({ story, reviews, t, config, onLoadResult }) => {
  const [historyResults, setHistoryResults] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    const results = await api.listResults(config);
    setHistoryResults(results);
  };

  const handleLoadHistoricalResult = async (runId: string) => {
    setLoading(true);
    setSelectedRunId(runId);
    try {
      const result = await api.getResultById(runId, config);
      if (result) {
        onLoadResult(result);
      }
    } catch (error) {
      console.error('Failed to load result:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleExportJSON = () => {
    if (!story) return;
    const exportData = { story, reviews, exported_at: new Date().toISOString() };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    if (!story) return;
    let markdown = `# ${story.title}\n\n**Generated by Idea2Paper** | ${new Date().toLocaleDateString()}\n\n---\n\n`;
    markdown += `## Abstract\n\n${story.abstract}\n\n`;
    if (story.introduction) markdown += `## Introduction\n\n${story.introduction}\n\n`;
    if (story.methodology) markdown += `## Methodology\n\n${story.methodology}\n\n`;
    if (story.experiments) markdown += `## Experiments\n\n${story.experiments}\n\n`;
    if (story.contributions && story.contributions.length > 0) {
      markdown += `## Contributions\n\n`;
      story.contributions.forEach((contrib, idx) => { markdown += `${idx + 1}. ${contrib}\n`; });
      markdown += `\n`;
    }
    if (reviews && reviews.length > 0) {
      markdown += `---\n\n## Anchored Review\n\n**Average Score:** ${(reviews.reduce((acc, r) => acc + r.score, 0) / reviews.length).toFixed(2)}/10\n\n`;
      reviews.forEach((review) => {
        markdown += `### ${review.reviewer} - ${review.role}\n\n**Score:** ${review.score.toFixed(2)}/10\n\n**Feedback:**\n\n${review.feedback}\n\n`;
        if (review.anchors && review.anchors.length > 0) {
          markdown += `**Anchored Papers:**\n\n`;
          review.anchors.slice(0, 3).forEach(anchor => { markdown += `- [${anchor.score10.toFixed(1)}/10] ${anchor.title}\n`; });
          if (review.anchors.length > 3) markdown += `- *+${review.anchors.length - 3} more papers*\n`;
          markdown += `\n`;
        }
      });
    }
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${story.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const averageScore = reviews.length > 0 ? (reviews.reduce((acc, curr) => acc + curr.score, 0) / reviews.length).toFixed(1) : 'N/A';

  return (
    <div className="flex flex-col lg:flex-row gap-6">
      {/* Left Sidebar - History - flex: 2 */}
      <div className="lg:flex-[2]">
        <div className="bg-white dark:bg-slate-800 rounded-3xl border border-slate-200 dark:border-slate-700 overflow-hidden transition-colors duration-300 sticky">
          <div className="p-4 border-b border-slate-100 dark:border-slate-700 bg-violet-50 dark:bg-violet-900/20">
            <div className="flex items-center gap-2">
              <History size={18} className="text-violet-500" />
              <h3 className="font-bold text-slate-800 dark:text-white text-sm">{t.results?.history_title || 'History'}</h3>
              <span className="ml-auto text-xs bg-violet-100 dark:bg-violet-900/30 text-violet-600 dark:text-violet-400 px-2 py-0.5 rounded-full font-bold">{historyResults.length}</span>
            </div>
          </div>
          <div className="p-3 max-h-[calc(100vh-200px)] overflow-y-auto">
            {historyResults.length === 0 ? (
              <div className="text-center py-8 text-slate-400 dark:text-slate-500 text-sm">No history yet</div>
            ) : (
              <div className="space-y-2">
                {historyResults.map((result) => (
                  <button key={result.run_id} onClick={() => handleLoadHistoricalResult(result.run_id)} disabled={loading}
                    className={`w-full text-left p-3 rounded-lg border transition-all group ${selectedRunId === result.run_id ? 'bg-violet-100 dark:bg-violet-900/40 border-violet-300 dark:border-violet-700' : 'bg-slate-50 dark:bg-slate-900 border-slate-200 dark:border-slate-700 hover:bg-violet-50 dark:hover:bg-violet-900/20 hover:border-violet-300 dark:hover:border-violet-700'}`}>
                    <h4 className="text-sm font-bold text-slate-900 dark:text-white mb-1 line-clamp-2 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">{result.title || result.user_idea}</h4>
                    <p className="text-xs text-slate-400 dark:text-slate-500">{new Date(result.created_at).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
                    {result.success && <span className="inline-flex items-center mt-1 text-[10px] font-bold text-green-600 dark:text-green-400">✓ Success</span>}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Paper Content - flex: 5 */}
      {!story ? (
        <div className="lg:flex-[8] flex flex-col items-center justify-center h-96 text-slate-400 dark:text-slate-500 bg-white dark:bg-slate-800 rounded-3xl border border-slate-200 dark:border-slate-700 border-dashed transition-colors duration-300">
          <History size={48} className="mb-4 opacity-30 text-violet-400" />
          <p className="text-lg font-medium text-slate-600 dark:text-slate-400">{t.results.no_story}</p>
          <p className="text-sm">{t.results.run_hint}</p>
        </div>
      ) : (
        <>
          <div className="lg:flex-[5]">
            <div className="bg-white dark:bg-slate-800 p-6 md:p-10 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 min-h-[800px] transition-colors duration-300">
                <div className="border-b-2 border-slate-50 dark:border-slate-700 pb-8 mb-8 text-center">
                  <h1 className="text-3xl md:text-4xl font-bold text-slate-900 dark:text-white leading-tight mb-6 font-serif tracking-tight">{story.title}</h1>
                  <div className="flex items-center justify-center gap-4 text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">
                    <span>{t.results.generated_by}</span><span className="text-slate-300 dark:text-slate-600">•</span><span>{new Date().toLocaleDateString()}</span>
                  </div>
                </div>
                <div className="mb-10 bg-slate-50 dark:bg-slate-900 p-6 rounded-2xl border border-slate-100 dark:border-slate-700">
                  <h3 className="text-xs font-bold uppercase tracking-widest text-slate-900 dark:text-slate-200 mb-3 text-center">{t.results.abstract}</h3>
                  <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-justify font-serif italic text-lg">{story.abstract}</p>
                </div>
                <div className="space-y-8">
                  <section><h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{t.results.intro}</h2><p className="text-slate-600 dark:text-slate-300 leading-7 whitespace-pre-line text-lg">{story.introduction || 'No introduction available.'}</p></section>
                  <section><h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{t.results.method}</h2><div className="pl-6 border-l-4 border-violet-200 dark:border-violet-900 py-1"><p className="text-slate-600 dark:text-slate-300 leading-7 whitespace-pre-line text-lg">{story.methodology || 'No methodology available.'}</p></div></section>
                  <section><h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{t.results.exp}</h2><p className="text-slate-600 dark:text-slate-300 leading-7 whitespace-pre-line text-lg">{story.experiments || 'No experiments available.'}</p></section>
                  <section><h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{t.results.contrib}</h2>
                    {story.contributions && story.contributions.length > 0 ? (
                      <ul className="list-disc pl-5 space-y-3 text-slate-600 dark:text-slate-300 text-lg marker:text-violet-500">{story.contributions.map((contribution, idx) => (<li key={idx} className="pl-2">{contribution}</li>))}</ul>
                    ) : (<p className="text-slate-600 dark:text-slate-300 leading-7 text-lg">No contributions available.</p>)}
                  </section>
                </div>
            </div>
          </div>

          {/* Right Sidebar - Reviews - flex: 3 */}
          <div className="lg:flex-[3] space-y-6">
            <div className="bg-white dark:bg-slate-800 p-6 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 transition-colors duration-300">
                <h3 className="font-bold text-slate-800 dark:text-white mb-4 text-sm uppercase tracking-wide">{t.results.export}</h3>
                <div className="grid grid-cols-2 gap-3">
                  <button onClick={handleExportJSON} className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-900 dark:bg-slate-700 text-white rounded-xl hover:bg-slate-800 dark:hover:bg-slate-600 transition-colors text-sm font-medium shadow-lg shadow-slate-200 dark:shadow-none"><Download size={16} /> JSON</button>
                  <button onClick={handleExportMarkdown} className="flex items-center justify-center gap-2 px-4 py-3 border-2 border-slate-100 dark:border-slate-600 text-slate-600 dark:text-slate-300 rounded-xl hover:border-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition-all text-sm font-medium"><Download size={16} /> MD</button>
                </div>
              </div>

              <div className="bg-white dark:bg-slate-800 p-6 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-700 transition-colors duration-300">
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-bold text-slate-800 dark:text-white text-sm uppercase tracking-wide">{t.results.anchored_review}</h3>
                  <div className="flex items-center gap-1.5 bg-yellow-50 dark:bg-yellow-900/20 px-3 py-1.5 rounded-full text-yellow-700 dark:text-yellow-400 font-bold border border-yellow-200 dark:border-yellow-900/30 shadow-sm"><Star size={14} className="fill-yellow-500 text-yellow-500" /><span className="text-sm">{averageScore}/10</span></div>
                </div>
                <div className="space-y-6">
                  {reviews.map((review, idx) => (
                    <div key={idx} className="relative pb-6 border-l-2 border-slate-100 dark:border-slate-700 pl-6 last:pb-0 group">
                      <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-white dark:bg-slate-800 border-4 border-slate-200 dark:border-slate-700 group-hover:border-violet-400 transition-colors"></div>
                      <div className="flex justify-between items-start mb-3">
                        <div><div className="text-sm font-bold text-slate-900 dark:text-slate-100">{review.reviewer}</div><div className="text-xs text-violet-600 dark:text-violet-400 font-medium">{review.role}</div></div>
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md ${review.score >= 8 ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300' : review.score >= 5 ? 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300' : 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300'}`}>{review.score.toFixed(2)}/10</span>
                      </div>
                      <div className="bg-slate-50 dark:bg-slate-900 p-4 rounded-2xl text-xs text-slate-600 dark:text-slate-400 relative leading-relaxed mb-3"><Quote size={14} className="absolute top-3 left-3 text-slate-300 dark:text-slate-600 -z-0" /><p className="relative z-10 pl-3">{review.feedback}</p></div>
                      {review.anchors && review.anchors.length > 0 && (
                        <div className="mt-3">
                          <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2">Anchored Against {review.anchors.length} Papers</div>
                          <div className="space-y-1.5">
                            {review.anchors.slice(0, 3).map((anchor, aidx) => (<div key={aidx} className="flex items-start gap-2 text-[10px] bg-white dark:bg-slate-800 p-2 rounded-lg border border-slate-100 dark:border-slate-700"><span className="flex-shrink-0 w-12 text-center font-bold text-slate-500 dark:text-slate-400">{anchor.score10.toFixed(1)}/10</span><span className="flex-1 text-slate-600 dark:text-slate-300 line-clamp-2">{anchor.title}</span></div>))}
                            {review.anchors.length > 3 && (<div className="text-[10px] text-slate-400 dark:text-slate-500 text-center py-1">+{review.anchors.length - 3} more papers</div>)}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-gradient-to-br from-blue-50 to-violet-50 dark:from-blue-900/20 dark:to-violet-900/20 p-6 rounded-3xl border border-blue-100/50 dark:border-blue-900/30 transition-colors duration-300">
                <h4 className="text-blue-900 dark:text-blue-300 font-bold mb-2 text-sm flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>{t.results.about_anchor}</h4>
                <p className="text-blue-800/70 dark:text-blue-300/70 text-xs leading-relaxed font-medium">{t.results.about_anchor_desc}</p>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
